name: NGINX-RTMP CI

on:
  push:
    branches:    
      - master
  pull_request:
    branches:
      - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master
    
    - name: Build & Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: lyekumchew/nginx-rtmp
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: ${{ github.workspace }}/.docker/Dockerfile
        workdir: ${{ github.workspace }}


